const DARK = {
  pageBg: 'bg-zinc-900',
  cardBg: 'bg-zinc-800',
  cardAltBg: 'bg-zinc-900',
  border: 'border-zinc-600',
  divider: 'border-zinc-600',
  rowBg: 'bg-zinc-800',
  rowActive: 'active:bg-zinc-700',
  sectionTitle: 'text-zinc-400',
  textPrimary: 'text-zinc-100',
  textSecondary: 'text-zinc-400',
  title: 'text-zinc-100',
  subtitle: 'text-zinc-100',
  subtext: 'text-zinc-400',
  iconBg: 'bg-zinc-700',
  iconColor: '#F8FAFC',
  icon: '#F8FAFC',
  chevron: '#A1A1AA',
  switchTrackOff: '#52525B',
  switchTrackOn: '#52525B',
  line: 'bg-zinc-700',
  emptyIcon: '#A1A1AA',
  albumEmptySecondary: 'text-zinc-500',
  avatarGradient: 'from-zinc-500 to-zinc-700',

  headerBg: 'bg-zinc-800',
  inputBg: 'bg-zinc-700',
  inputText: 'text-zinc-100',
  inputBorder: 'border-zinc-600',
  inputPlaceholder: '#A1A1AA',
  count: 'text-zinc-400',
  loading: '#F8FAFC',
  loadingText: 'text-zinc-400',

  headerText: 'text-zinc-100',
  pickerTitle: 'text-zinc-100',
  pickerSub: 'text-zinc-400',
  pickerCircle: 'bg-zinc-100',
  pickerCircleIcon: '#111111',
  infoIcon: '#A1A1AA',
  infoText: 'text-zinc-400',

  secondaryBtn: 'bg-zinc-700',
  secondaryText: 'text-zinc-200',
  button: 'bg-zinc-100',
  buttonText: 'text-zinc-900',
  footer: 'text-zinc-400',

  menuBg: 'bg-zinc-800',
  menuBorder: 'border-zinc-600',
  rowBorder: 'border-zinc-700',
  text: 'text-zinc-100',
  fabBg: 'bg-zinc-100',
  fabIcon: '#111111',

  sheetBg: 'bg-zinc-800',
  sheetBorder: 'border-zinc-700',
  body: 'text-zinc-300',
  tagBg: 'bg-zinc-700',
  tagText: 'text-zinc-300',
  placeholderBg: 'bg-zinc-700',
  dotBg: 'bg-[#F8FAFC]',
};

const LIGHT = {
  pageBg: 'bg-gray-50',
  cardBg: 'bg-white',
  cardAltBg: 'bg-white',
  border: 'border-gray-100',
  divider: 'border-gray-100',
  rowBg: 'bg-white',
  rowActive: 'active:bg-gray-50',
  sectionTitle: 'text-gray-500',
  textPrimary: 'text-gray-900',
  textSecondary: 'text-gray-500',
  title: 'text-black',
  subtitle: 'text-black',
  subtext: 'text-gray-400',
  iconBg: 'bg-gray-100',
  iconColor: '#111111',
  icon: '#111111',
  chevron: '#9CA3AF',
  switchTrackOff: '#E5E7EB',
  switchTrackOn: '#000000',
  line: 'bg-gray-200',
  emptyIcon: '#C8C8C8',
  albumEmptySecondary: 'text-gray-300',
  avatarGradient: 'from-zinc-500 to-zinc-700',

  headerBg: 'bg-white',
  inputBg: 'bg-gray-100',
  inputText: 'text-gray-900',
  inputBorder: 'border-gray-300',
  inputPlaceholder: '#6B7280',
  count: 'text-gray-400',
  loading: '#000000',
  loadingText: 'text-gray-500',

  headerText: 'text-black',
  pickerTitle: 'text-black',
  pickerSub: 'text-gray-500',
  pickerCircle: 'bg-[#121212]',
  pickerCircleIcon: 'white',
  infoIcon: '#999999',
  infoText: 'text-gray-400',

  secondaryBtn: 'bg-gray-100',
  secondaryText: 'text-gray-700',
  button: 'bg-black',
  buttonText: 'text-white',
  footer: 'text-gray-500',

  menuBg: 'bg-white',
  menuBorder: 'border-gray-200',
  rowBorder: 'border-gray-100',
  text: 'text-black',
  fabBg: 'bg-[#121212]',
  fabIcon: 'white',

  sheetBg: 'bg-white',
  sheetBorder: 'border-gray-100',
  body: 'text-gray-600',
  tagBg: 'bg-gray-100',
  tagText: 'text-gray-600',
  placeholderBg: 'bg-gray-200',
  dotBg: 'bg-[#111111]',
};

const withPalette = (base, overrides) => ({ ...base, ...overrides });

export const THEME_OPTIONS = [
  {
    id: 'light',
    label: 'Light',
    description: 'Clean gallery mode',
    icon: 'sunny-outline',
    isDark: false,
    swatch: ['#F9FAFB', '#111827'],
  },
  {
    id: 'dark',
    label: 'Dark',
    description: 'Midnight neutral',
    icon: 'moon-outline',
    isDark: true,
    swatch: ['#18181B', '#F8FAFC'],
  },
  {
    id: 'midnight',
    label: 'Midnight',
    description: 'Deep blue focus',
    icon: 'sparkles-outline',
    isDark: true,
    swatch: ['#0F172A', '#38BDF8'],
  },
  {
    id: 'forest',
    label: 'Forest',
    description: 'Muted green dark',
    icon: 'leaf-outline',
    isDark: true,
    swatch: ['#102018', '#86EFAC'],
  },
  {
    id: 'ocean',
    label: 'Ocean',
    description: 'Airy blue daylight',
    icon: 'water-outline',
    isDark: false,
    swatch: ['#ECFEFF', '#0284C7'],
  },
  {
    id: 'sunset',
    label: 'Sunset',
    description: 'Warm peach paper',
    icon: 'partly-sunny-outline',
    isDark: false,
    swatch: ['#FFF7ED', '#F97316'],
  },
  {
    id: 'rose',
    label: 'Rose',
    description: 'Soft pink gallery',
    icon: 'rose-outline',
    isDark: false,
    swatch: ['#FFF1F2', '#E11D48'],
  },
];

const PALETTES = {
  light: LIGHT,
  dark: DARK,
  midnight: withPalette(DARK, {
    pageBg: 'bg-slate-950',
    cardBg: 'bg-slate-900',
    cardAltBg: 'bg-slate-950',
    border: 'border-slate-700',
    divider: 'border-slate-700',
    rowBg: 'bg-slate-900',
    rowActive: 'active:bg-slate-800',
    sectionTitle: 'text-sky-300',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-400',
    title: 'text-slate-100',
    subtext: 'text-slate-400',
    iconBg: 'bg-slate-800',
    iconColor: '#BAE6FD',
    icon: '#BAE6FD',
    chevron: '#7DD3FC',
    headerBg: 'bg-slate-900',
    inputBg: 'bg-slate-800',
    inputText: 'text-slate-100',
    inputBorder: 'border-slate-700',
    inputPlaceholder: '#94A3B8',
    pickerCircle: 'bg-sky-200',
    pickerCircleIcon: '#0F172A',
    button: 'bg-sky-200',
    buttonText: 'text-slate-950',
    fabBg: 'bg-sky-200',
    fabIcon: '#0F172A',
    menuBg: 'bg-slate-900',
    menuBorder: 'border-slate-700',
    rowBorder: 'border-slate-800',
    sheetBg: 'bg-slate-900',
    sheetBorder: 'border-slate-700',
    tagBg: 'bg-slate-800',
    tagText: 'text-sky-100',
    placeholderBg: 'bg-slate-800',
    dotBg: 'bg-sky-200',
  }),
  forest: withPalette(DARK, {
    pageBg: 'bg-emerald-950',
    cardBg: 'bg-emerald-900',
    cardAltBg: 'bg-emerald-950',
    border: 'border-emerald-800',
    divider: 'border-emerald-800',
    rowBg: 'bg-emerald-900',
    rowActive: 'active:bg-emerald-800',
    sectionTitle: 'text-emerald-300',
    textPrimary: 'text-emerald-50',
    textSecondary: 'text-emerald-200',
    title: 'text-emerald-50',
    subtext: 'text-emerald-200',
    iconBg: 'bg-emerald-800',
    iconColor: '#BBF7D0',
    icon: '#BBF7D0',
    chevron: '#86EFAC',
    headerBg: 'bg-emerald-900',
    inputBg: 'bg-emerald-800',
    inputText: 'text-emerald-50',
    inputBorder: 'border-emerald-700',
    inputPlaceholder: '#A7F3D0',
    pickerCircle: 'bg-emerald-200',
    pickerCircleIcon: '#052E16',
    button: 'bg-emerald-200',
    buttonText: 'text-emerald-950',
    fabBg: 'bg-emerald-200',
    fabIcon: '#052E16',
    menuBg: 'bg-emerald-900',
    menuBorder: 'border-emerald-800',
    rowBorder: 'border-emerald-800',
    sheetBg: 'bg-emerald-900',
    sheetBorder: 'border-emerald-800',
    tagBg: 'bg-emerald-800',
    tagText: 'text-emerald-100',
    placeholderBg: 'bg-emerald-800',
    dotBg: 'bg-emerald-200',
  }),
  ocean: withPalette(LIGHT, {
    pageBg: 'bg-cyan-50',
    cardBg: 'bg-white',
    border: 'border-cyan-100',
    divider: 'border-cyan-100',
    rowActive: 'active:bg-cyan-50',
    sectionTitle: 'text-sky-600',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-sky-700',
    title: 'text-slate-950',
    iconBg: 'bg-cyan-100',
    iconColor: '#0369A1',
    icon: '#0369A1',
    chevron: '#0284C7',
    switchTrackOn: '#0284C7',
    headerBg: 'bg-white',
    inputBg: 'bg-cyan-50',
    inputBorder: 'border-cyan-200',
    pickerCircle: 'bg-sky-600',
    pickerCircleIcon: 'white',
    button: 'bg-sky-700',
    buttonText: 'text-white',
    fabBg: 'bg-sky-700',
    fabIcon: 'white',
    menuBorder: 'border-cyan-100',
    rowBorder: 'border-cyan-100',
    tagBg: 'bg-cyan-100',
    tagText: 'text-sky-800',
    placeholderBg: 'bg-cyan-100',
    dotBg: 'bg-sky-700',
  }),
  sunset: withPalette(LIGHT, {
    pageBg: 'bg-orange-50',
    cardBg: 'bg-white',
    border: 'border-orange-100',
    divider: 'border-orange-100',
    rowActive: 'active:bg-orange-50',
    sectionTitle: 'text-orange-600',
    textPrimary: 'text-stone-950',
    textSecondary: 'text-orange-700',
    title: 'text-stone-950',
    iconBg: 'bg-orange-100',
    iconColor: '#C2410C',
    icon: '#C2410C',
    chevron: '#EA580C',
    switchTrackOn: '#EA580C',
    headerBg: 'bg-white',
    inputBg: 'bg-orange-50',
    inputBorder: 'border-orange-200',
    pickerCircle: 'bg-orange-600',
    pickerCircleIcon: 'white',
    button: 'bg-orange-700',
    buttonText: 'text-white',
    fabBg: 'bg-orange-700',
    fabIcon: 'white',
    menuBorder: 'border-orange-100',
    rowBorder: 'border-orange-100',
    tagBg: 'bg-orange-100',
    tagText: 'text-orange-800',
    placeholderBg: 'bg-orange-100',
    dotBg: 'bg-orange-700',
  }),
  rose: withPalette(LIGHT, {
    pageBg: 'bg-rose-50',
    cardBg: 'bg-white',
    border: 'border-rose-100',
    divider: 'border-rose-100',
    rowActive: 'active:bg-rose-50',
    sectionTitle: 'text-rose-600',
    textPrimary: 'text-zinc-950',
    textSecondary: 'text-rose-700',
    title: 'text-zinc-950',
    iconBg: 'bg-rose-100',
    iconColor: '#BE123C',
    icon: '#BE123C',
    chevron: '#E11D48',
    switchTrackOn: '#E11D48',
    headerBg: 'bg-white',
    inputBg: 'bg-rose-50',
    inputBorder: 'border-rose-200',
    pickerCircle: 'bg-rose-600',
    pickerCircleIcon: 'white',
    button: 'bg-rose-700',
    buttonText: 'text-white',
    fabBg: 'bg-rose-700',
    fabIcon: 'white',
    menuBorder: 'border-rose-100',
    rowBorder: 'border-rose-100',
    tagBg: 'bg-rose-100',
    tagText: 'text-rose-800',
    placeholderBg: 'bg-rose-100',
    dotBg: 'bg-rose-700',
  }),
};

export const DEFAULT_THEME_ID = 'light';

export const isThemeId = (value) => {
  return THEME_OPTIONS.some((theme) => theme.id === value);
};

export const getThemeMeta = (themeId) => {
  return THEME_OPTIONS.find((theme) => theme.id === themeId) || THEME_OPTIONS[0];
};

export const isDarkTheme = (themeId) => {
  return Boolean(getThemeMeta(themeId).isDark);
};

export const getThemeColors = (theme) => {
  if (typeof theme === 'string') {
    return PALETTES[theme] || LIGHT;
  }

  return theme ? DARK : LIGHT;
};
